spring:
  datasource:
    url: jdbc:mysql://www.bswt.org/bswtsermons
    username: tbholdren
    password: r7ZhikTunkPR7RVB
    
bswt:
  api:
    rest:
      secret: bswt-secret
      
      admin:
        requiredRoles: admin
      
      subjects:
        - name: admin
          secret: admin-secret
          claims: 
            - admin