spring:
  datasource:
    url: jdbc:mysql://www.bswt.org/bswtsermons
    username: tbholdren
    password: r7ZhikTunkPR7RVB
    
bswt:
  api:
    resourceId: bswt
    credentials:
      clientCredentials:
        - clientId: trusted-app
          grantTypes:
            - client_credentials
          authorities:
            - ROLE_TRUSTED_CLIENT
          scopes:
            - read
            - write
          resourceId: bswt
          accessTokenValiditySeconds: 3600
          secret: d4e63d07-8fb6-440f-97d1-95344df8125a